check_edible/urls.py
from django.urls import path
from . import views

app_name = "check_edible"
urlpatterns = [
        path('', views.index, name='index'),
        path('upload', views.upload, name='upload'),
        path('result', views.result, name='result'),

        path('search', views.search, name='search'),
        
]

gaenyang/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('check_edible.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

check_edible/models.py
from django.db import models

# Create your models here.

check_edible/forms.py
from django.db import models
from django import forms

class UploadForm(forms.Form):
    CHOICES=[('dog','dog'), ('cat','cat')]
    attrs_radio_button = {'class': 'radio-control', }
    attrs_image_button = {'class': 'image-control', 'accept': 'image/*;capture=camera' }

    pet_type = forms.ChoiceField(
        widget=forms.RadioSelect(attrs=attrs_radio_button), 
        choices=CHOICES, 
        label="Pet type")
        
    food_image = forms.ImageField(label="Food for check")

check_edible/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .forms import UploadForm

import os
import pandas as pd
import tensorflow as tf
from PIL import Image, ImageOps
import numpy as np

# Create your views here.
def index(request):
    return render(request, 'check_edible/base.html', {})


def upload(request):
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            pet_type = form.cleaned_data['pet_type']
            food_image = form.cleaned_data['food_image']

            form.save() 

            # UserInput.objects.create(pet_type=pet_type, food_image=food_image)
            return redirect('result', {'pet_type': pet_type, 'food_image': food_image})
    else:
        form = UploadForm()

    return render(request, "check_edible/upload.html", {'form': form}) 


def result(request):
    # Edible data
    fruits = ['almond', 'apple', 'broccoli', 'carrot', 'grape', 'mandarin', 'melon', 'onion', 'welshOnion' ]
    fruits_kor = {
        'almond': '아몬드', 
        'apple': '사과', 
        'broccoli': '브로콜리', 
        'carrot': '당근', 
        'grape': '포도',
        'mandarin': '귤', 
        'melon': '참외', 
        'onion': '양파',
        'welshOnion': '대파' }
    cat = [False, True, True, True, False, True, True, False, False]
    dog = [False, True, True, True, False, True, True, False, False]
    edible_table = pd.DataFrame(index=fruits, columns = ['dog', 'cat'])
    edible_table['dog'] = dog
    edible_table['cat'] = cat

    # Precaution edible_table
    dog = [
        '아몬드는 고지방 식품이기 때문에 췌장염 위험이 있습니다. 아몬드를 통째로 삼킬 경우에는 위장관 폐쇄의 위험이 있으니 급여하지 않는 것이 좋습니다.', 
        '사과의 씨앗, 껍질, 심 부분을 제거 한 후 급여해주세요. 알러지나 부작용이 있을 수 있으니, 소량 급여를 통해 부작용을 확인하세요. 과량 섭취시에는 설사나 복통을 유발할 수 있습니다.', 
        '브로콜리는 먹어도 되지만, 소량만 주어야 합니다. 양념이나 기름으로 구운상태로 주면 안 됩니다. 간이 안된 상태로 준다면 쪄서 주거나 생으로 줘도 됩니다. 줄기 부분이 식도에 걸릴 수 있기 때문에 잘게 잘라서 주는 것이 좋습니다.', 
        '당근은 눈 건강에 좋으며, 당근에 함유되어있는 비타민 A는 자궁건강에 좋습니다. 생당근을 잘게 썰어서 급여하거나 찐 당근도 급여 가능합니다.', 
        '중독을 일으켜 급성 신부전이 올 수 있습니다. 구토, 설사 등을 동반하며 사망에 이를 수 있어 위험합니다.', 
        '귤 껍질과 알맹이에 있는 흰색 부분을 제거하시고, 급여해주세요. 당이 높기 때문에 과도한 섭취는 금물입니다.', 
        '껍질과 씨 부분을 제거한 후 급여해주세요.', 
        '양파 내의 N-propyl disulfide라는 독성 성분이 적혈구를 파괴하여 빈혈을 야기할 수 있습니다. ', 
        '양파와 마찬가지로 독성 성분이 적혈구를 파괴하고, 용혈성 빈혈 증상이 일어날 수 있습니다. 심하면 사망에 이를 수 있으니 주의하세요.']
    cat = [
        '아몬드를 통째로 삼킬 경우에는 위장관 폐쇄의 위험이 있으니 급여하지 않는 것이 좋습니다.', 
        '사과의 씨앗은 \'시안배당체\'라는 물질이 포함되어 있어 고양이에게 독이 될 수 있으니 꼭 제거하고 급여하세요. 또한, 고양이에게 사과를 너무 많이 주면 소화 불량을 일으킬 수 있으므로 적당량 급여해 주세요.', 
        '브로콜리는 항암 효과가 뛰어납니다. 비타민 C가 레몬의 두 배 이상 함유되어 있어 감기 예방과 면역력 증가에도 도움이 됩니다. 또한, 칼슘도 풍부해 골다공증 및 심장병 예방에도 도움이 되는 것으로 알려져 있습니다. ', 
        '고양이는 당근을 섭취해도 괜찮지만, 비타민 A를 공급받을 수 없기 때문에 당근이 몸에 좋다고 하기는 힘듭니다. 다만 당근에는 식이 섬유가 많기 때문에 변비에 효과가 있을 수 있습니다. 하지만 과잉 섭취 했을 경우 간에 부담을 주거나 요로결석이 생길 위험이 있으니 주의가 필요합니다. ', 
        '강아지와 마찬가지로 고양이도 포도에 중독 증상을 나타낸 보고가 있으므로 주의해야 합니다. 특히 위험한 것이 급성 신부정 증상입니다. 급성 신부전은 신장이 제대로 작동하지 않아 사망까지 다다를 수 있는 무서운 질병이므로 포도를 급여하는 것은 매우 위험합니다.', 
        '고양이는 귤 껍질에 함유된 리모넨이라는 물질을 분해하지 못합니다. 과육, 과즙만 주는 것은 괜찮지만 주의가 필요합니다. 또한, 껍질의 즙이 닿으면 피부 염증을 일으키는 경우도 있으므로 주의가 필요하다.', 
        '참외에는 비타민 C가 풍부하게 함유되어 있어 피로회복에 도움이 되며, 과육의 수분 함량도 90% 이상이어서 섭취시 수분 보충에 많은 도움이 됩니다. 단, 참외 씨는 소화가 잘 되지 않거나 배탈을 유발할 수 있으므로 반드시 제거하고 과육만 적당한 크기로 썰어서 줍시다. 고양이 전용 우유와 함께 믹서기에 넣고 갈아서 주어도 괜찮습니다.', 
        '고양이에게 양파는 양파의 allyl propyl disulfide라는 성분이 헤모글로빈을 산화시켜 적혈구를 파괴합니다. 적혈구가 너무 많이 파괴되면 용혈성 빈혈이 생길 수 있습니다. 또한 이 성분은 가열해도 성질이 변하지 않기 때문에 요리시에 주의하셔야 합니다.', 
        '양파와 마찬가지로 독성 성분이 적혈구를 파괴하고, 용혈성 빈혈 증상이 일어날 수 있습니다. 심하면 사망에 이를 수 있으니 주의하세요.']
    precaution_table = pd.DataFrame(index=fruits, columns = ['dog', 'cat'])
    precaution_table['dog'] = dog
    precaution_table['cat'] = cat

    
    pet_type = request.POST['pet_type']
    food_image = request.FILES['food_image']
    
    # model inference part
    np.set_printoptions(suppress=True)

    modelpath = './check_edible/saved_model'
    model = tf.keras.models.load_model(modelpath)

    # Image preprocess
    image_size = 100
    # img_path = os.path.join(food_image)
    img = Image.open(food_image)
    img = img.resize((image_size, image_size))
    img = tf.keras.preprocessing.image.img_to_array(img)
    img = tf.expand_dims(img, 0)

    prediction = model.predict(img)
    score = tf.nn.softmax(prediction[0])
    prediction = fruits[np.argmax(score)]

    # data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
    # image = Image.open(food_image)
    # size = (224, 224)
    # image = ImageOps.fit(image, size, Image.ANTIALIAS)
    # image_array = np.asarray(image)
    # normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
    # data[0] = normalized_image_array

    # prediction = model.predict(data)


    # # look for the mapping edible_table whether it is edible
    is_edible = edible_table[pet_type][prediction]
    precaution = precaution_table[pet_type][prediction]

    kor_name = fruits_kor[prediction]
    # Gather variables for rendering and throw it
    context = {
        'pet_type': pet_type,
        'food_image': food_image,
        'food_type': prediction,
        'is_edible': is_edible,
        'precaution': precaution,
        'kor_name': kor_name,
    }
    return render(request, "check_edible/result.html", context)


def search(request):
    keyword = request.GET.get('keyword')
    engine = request.GET.get('engine')

    if engine == 'google':
        search_url ='https://www.google.co.kr/search?q='+ keyword + '&tbm=isch'
    elif engine == 'naver':
        search_url = 'https://search.naver.com/search.naver?where=image&sm=tab_jum&query=' + keyword

    
    return HttpResponseRedirect(search_url)

check_edible/templates/check_edible/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="utf-8" />
  <title>먹어도 되개냥? &mdash; CaCaO(조)</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
  <meta name="keywords" content="some keywords that best describe your business" />
  <meta name="description" content="a short description of your company" />
  <meta name="author" content="SRPACDY" />

  <!-- Mobile Specific Metas
        ================================================== -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

  <!-- CSS
        ================================================== -->
        
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css" media="screen" />
  <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}" type="text/css" media="screen" />
  <link rel="stylesheet" href="{% static 'css/layout.css' %}" type="text/css" media="screen" />
  <link rel="stylesheet" href="{% static 'css/background.css' %}" type="text/css" media="screen" />
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css" media="screen" />

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" />
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}" />
  <link rel="stylesheet" href="{% static 'fonts/NanumBarunpenB/NanumBarunpenB.css' %}" />
  <link rel="stylesheet" href="{% static 'css/aos.css' %}" />
  <link rel="stylesheet" href="{% static 'css/tooptip.css' %}" />

  <!-- Favicons
        ================================================== -->
  <link rel="shortcut icon" href="{% static 'images/icon.ico' %}" />
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet" />

<!-- Popover -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<style>
.radio-control {
  font-size: 2em;
}
.image-control {
  overflow: auto;
}
</style>

</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300" id="home-section">

  <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5f6466e3577e7c47"></script>
  <script type="text/javascript" src="{% static 'js/Search.js' %}" charset="utf-8"></script>



  <!-- Primary Page Layout
    ====================================================================== -->
  <div class="header bg">
    <div class="container">
      <div class="row">
        <header class="col-xs-12 text-center">
          <div class="logo" style="margin-bottom:auto;">
            <a href="upload"><img src="{% static 'images/catdoglogo2.png' %}" /></a>
          </div>
          <p><h1 style="font-family: NanumBarunpenB; font-size: 5vw">
              Providing the right way to eat and staying healthy with your pet
            </h1></p>
        </header>
      </div>
    </div>
  </div>

  <!-- 먹어도 되개냥 position -->
  <div class="about" id="aout">
    <div class="container">
      <div class="row">
        <div class="col-xs-10 text-center">
          <div class="about-content">
            <h2>
              <p style="font-family: NanumBarunpenB" style="font-weight: bold">
                Welcome to '먹어도 되개냥'
              </p>
            </h2>
            <p style="font-family: NanumBarunpenB">
              Would our pets eat the ingredients we eat? Check it out in here!
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>






  {% block uploadform %}
  {% endblock %}


  {% block result %}
  {% endblock %}



  <!-- social position -->
  <div class="social">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 text-center">
          <div class="social-content">
            <h2>
              <p style="font-family: NanumBarunpenB">Team member</p>
            </h2>
            <div class="grid clearfix" style="padding-bottom: 40px;">
              <div class="col-sm-3 text-center">
                <figure>
                  <img src="{% static 'images/profile/001.png' %}" alt="Image" class="img-fluid" />
                </figure>
                <p style="font-family: NanumBarunpenB">Ji-Hyang Park</p>
              </div>
              <div class="col-sm-3 text-center">
                <figure>
                  <img src="{% static 'images/profile/002.png' %}" alt="Image" class="img-fluid" />
                </figure>
                <p style="font-family: NanumBarunpenB">Chae-ri Kim</p>
              </div>
              <div class="col-sm-3 text-center">
                <figure>
                  <img src="{% static 'images/profile/003.png' %}" alt="Image" class="img-fluid" />
                </figure>
                <p style="font-family: NanumBarunpenB">Hakjun Kim</p>
              </div>
              <div class="col-sm-3 text-center">
                <figure>
                  <img src="{% static 'images/profile/004.png' %}" alt="Image" class="img-fluid" />
                </figure>
                <p style="font-family: NanumBarunpenB">Yoon-mi Kim</p>
              </div>
            </div>
            <!-- Go to www.addthis.com/dashboard to customize your tools -->
            <div class="addthis_inline_share_toolbox"></div>
          </div>
        </div>
      </div>
    </div>
  </div>



  <!-- footer position -->
  <div class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          <div class="copy">
            <p style="font-family: NanumBarunpenB">
              Thank You. &copy;2020
              <a href="" target="_blank">CaCaO(조)
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- JS
        ================================================== -->

  <script type="text/javascript" src="{% static 'js/jquery-1.11.0.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/scroll.js' %}" charset="utf-8"></script>
  <script type="text/javascript" src="{% static 'js/jquery.countdown.js' %}" charset="utf-8"></script>
  <script type="text/javascript" src="{% static 'js/countdown.js' %}" charset="utf-8"></script>
  <script type="text/javascript" src="{% static 'js/supersized.3.2.7.js' %}" charset="utf-8"></script>
  <script type="text/javascript" src="{% static 'js/images.js' %}" charset="utf-8"></script>
  <script type="text/javascript" src="{% static 'js/form.js' %}" charset="utf-8"></script>

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
  <script src="{% static 'js/jquery.sticky.js' %}"></script>
  <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
  
  
  <!-- Popover script -->
  <script>
  $(function(){$('[data-toggle="popover"]').popover()})
  $('button#').on('click', function(e) {e.preventDefault(); return true;});
  </script>


  <!-- End Document
        ================================================== -->

</body>

</html>

check_edible/templates/check_edible/index.html
{% extends 'check_edible/base.html' %}

check_edible/templates/check_edible/result.html
{% extends 'check_edible/base.html' %}
{% load static %}
{% block result %}

<div class="contact bg">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h1>
                    <p style="font-family: NanumBarunpenB; padding-bottom: 1.25em">Analysis</p>
                </h1>
            </div>
            <div class="col-md-12" style="text-align: center; ">
                <div
                    style="display:inline-block; vertical-align:middle; font-family: NanumBarunpenB; text-align: center; font-size:1.25em; padding-bottom: 15px;">
                    <p><b>Your pet</b></p>
                    {% if pet_type == "cat" %}
                    <img src="{% static 'images/pets/cat.png' %}" width="150" height="150" />
                    {% elif pet_type == "dog" %}
                    <img src="{% static 'images/pets/dog.png' %}" width="150" height="150" />
                    {% endif %}
                </div>
                <div
                    style="display:inline-block; vertical-align:middle; font-family: NanumBarunpenB; text-align: center; font-size:1.25em; padding-bottom: 15px;">
                    <p><b>Food: {{ kor_name }}</b></p>
                    {% if food_type == "almond" %}
                    <img src="{% static 'images/foods/almond.png' %}" width="150" height="150" />
                    {% elif food_type == "apple" %}
                    <img src="{% static 'images/foods/apple.png' %}" width="150" height="150" />
                    {% elif food_type == "broccoli" %}
                    <img src="{% static 'images/foods/broccoli.png' %}" width="150" height="150" />
                    {% elif food_type == "carrot" %}
                    <img src="{% static 'images/foods/carrot.png' %}" width="150" height="150" />
                    {% elif food_type == "grape" %}
                    <img src="{% static 'images/foods/grape.png' %}" width="150" height="150" />
                    {% elif food_type == "mandarin" %}
                    <img src="{% static 'images/foods/mandarin.png' %}" width="150" height="150" />
                    {% elif food_type == "melon" %}
                    <img src="{% static 'images/foods/melon.png' %}" width="150" height="150" />
                    {% elif food_type == "onion" %}
                    <img src="{% static 'images/foods/onion.png' %}" width="150" height="150" />
                    {% elif food_type == "welshOnion" %}
                    <img src="{% static 'images/foods/welshOnion.png' %}" width="150" height="150" />
                    {% endif %}
                </div>
                <div
                    style="display:inline-block; vertical-align:middle; font-family: NanumBarunpenB; text-align: center; font-size:1.25em; padding-bottom: 15px;">
                    <p><b>Is it edible?</b></p>
                    {% if is_edible %}
                    <img src="{% static 'images/true.png' %}" width="150" height="150" />
                    {% else %}
                    <img src="{% static 'images/false.png' %}" width="150" height="150" />
                    {% endif %}
                </div>
            </div>


        </div>
        <div style="font-family: NanumBarunpenB; font-size:1.5em; text-align: center; padding-top: 10px;">
            <strong>{{ precaution }}</strong></div>
    </div>
</div>

{% endblock %}

check_edible/templates/check_edible/upload.html
{% extends 'check_edible/base.html' %}
{% load static %}

{% block uploadform %}
<div class="features">
  <div class="container">
    <div class="text-center">
      <h2 style="font-family: NanumBarunpenB;">
        Today, What kind of snack would you like to give your pet?
      </h2>


      <div class="col-xs-12 text-center">
        <form action="{% url 'check_edible:result' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% comment %} {{ form.as_p }} {% endcomment %}

          <div class="about-content">
            <p style="font-family: NanumBarunpenB">반려동물의 종류를 선택하세요</p>

            <label name="dog" class="btn btn-lg ">
              <input type="radio" name="pet_type" value="dog" width="150" height="150">
              <img src="{% static 'images/pets/dog.png' %}">
            </label>

            <label  name="cat" class="btn btn-lg ">
              <input type="radio" name="pet_type" value="cat" width="150" height="150">
              <img src="{% static 'images/pets/cat.png' %}">
            </label>
          </div>

          <div class="about-content">
            <p style="font-family: NanumBarunpenB">식재료를 올려주세요</p>
            <label for="food_image">
              <input type="file" name="food_image" id="food_image" accept="image/*;capture=camera"
                style="border: none; display: none;">
              <img src="{% static 'images/camera.png'%}" width="150" height="102" />
            </label>


            <div class="about-content">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>


<!-- Search position -->
<div class="subscribe" id="subscribe">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 text-center">
        <div class="subscribe-form">
          <h3 style="font-family: NanumBarunpenB;">If you don't have a picture, Search here.</h3>

          <form action="search" class="search" method="get" target="_blank">
            <select class="SelectSearch" name="engine">
              <option id="google" value="google" style="background-color: #D6D6D6;">Google</option>
              <option id="naver" value="naver" style="background-color: #D6D6D6;">Naver</option>
            </select>

            <input id="search" class="keyword" type="text" name="keyword" maxlength="255" value="{{ search_string }}"
              autocomplete="off" placeholder="Search here" />
            <input type="submit" value="Search" />
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %} {% comment %}
<div class="col-sm-6 text-center">
  <i class="fa fa-mobile fa-5x"></i>
  <b>Photo shoot</b>
  <p style="font-family: NanumBarunpenB">
    Click the photo icon and Take a ingredients picture
  </p>
  <label class="btn btn-primary btn-file">
    Photo Shoot
    <input style="display: none" type="file" accept="image/*" capture="camera" />
  </label>
</div>

<div class="col-sm-5 text-center">
  <i class="fa fa-picture-o fa-4x"></i>
  <b> Add Image</b>
  <p style="font-family: NanumBarunpenB">
    Click the Upload button and add image
  </p>

  <label class="btn btn-primary btn-file">
    Add image
    <input style="display: none" type="file" />
  </label>
</div>
{% endcomment %}